version: "3.9"
services:
  postgres:
    image: postgres
    environment:
      - "POSTGRES_USER=root"
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_DB=postgres"
    ports:
      - "5432:5432"
  backend:
    image: feluxerich/notenapp-backend:latest
    environment:
      - "SQLALCHEMY_DATABASE_URL=postgresql://root:postgres@postgres:5432/postgres"
    ports:
      - "1337:1337"
